### PR TITLE
Allow CORS Fixes #122

### LINKED ISSUE #122: Cross origin requests are blocked
```
Joomla.request({
    url: 'https://downloads.joomla.org/api/v1/releases/cms',
    onSuccess: function(response, xhr) {
        console.log(response);
    }
})
```

I'd normally expected a response with this, however I'm getting the following:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://downloads.joomla.org/api/v1/releases/cms. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://downloads.joomla.org/api/v1/releases/cms. (Reason: CORS request did not succeed).

Same applies for `http://update.joomla.org/core/list.xml`.

### PR DESCRIPTION
**Pull request by zero-24**
cc @mbabker @C-Lodder Fixes #122 (already pushed to the live site)

### CODE REVIEW

**Comment by C-Lodder** [comment]
@zero-24 @mbabker  - Ajax request still not working. Returning the same error.

**Comment by mbabker** [comment]
Same change needed in the root `.htaccess` only for `/api` directory?  Or should it not matter since the directory has its own config?  (Yeah, I'm guessing here, I haven't done much as it relates to CORS and when I do need something like it I just use a PHP middleman script to do server-to-server versus client-to-server stuff)

**Comment by C-Lodder** [comment]
If you want to try manually added it to the other `.htaccess` file, I can letr you know if it works or not

**Comment by mbabker** [comment]
I don't know if it matters any but I added `Header always set Access-Control-Allow-Methods "GET"` to the `.htaccess` file and my quick test worked out OK.  Can you double check?

```js
$.ajax({
    type: 'GET',
    url: 'https://downloads.joomla.org/api/v1/releases/cms',
    success: function success() {
        console.log(arguments);
    },
    error: function error() {
        console.log(arguments);
    }
});
```

**Comment by C-Lodder** [comment]
Sure, give me a couple of hours till I'm home

**Comment by C-Lodder** [comment]
Ok seems to work with a jQuery ajax request but not fetch or xhr

**Comment by C-Lodder** [comment]
All working now. Thanks @mbabker. It won't work with a standard `Joomla.request()` though, but got an alternative

**Comment by zero-24** [comment]
hmm i have tested the original code in the issue and even without the changes here by Michael the request worked good?

**Comment by mbabker** [comment]
There's a quirk in the `Joomla.request()` object Dimitris pointed out on one of the recent 4.0 PRs.  AFAIK things are working OK with either jQuery's `.ajax()` handler or a plain `XMLHttpRequest` object.  There isn't anything else we'd need to change on our end.

**Comment by zero-24** [comment]
ok fine for me 👍

**Comment by C-Lodder** [comment]
Cool, thanks both for fixing this. Much appreciated

**Pull request merged**
