### PR TITLE
Use ->visualgroup_id(1) over category_id(0)

### PR DESCRIPTION
**Pull request by zero-24**
https://github.com/joomla/downloads.joomla.org/issues/271

Thanks & cc @Llewellynvdm

### CODE REVIEW

**Comment by HLeithner** [comment]
looks better now thx @zero-24 & @Llewellynvdm

**Comment by wilsonge** [comment]
This looks like it’s only returning the joomla 1.0 releases now? Not all cms releases?

**Comment by Llewellynvdm** [comment]
This is what is one the live system:
```php
	/**
	 * Execute the controller.
	 *
	 * @return  boolean
	 *
	 * @since   1.0
	 */
	public function execute()
	{
		// This will autoload the ARS files
		$container = Container::getInstance('com_ars');

		/** @var \Akeeba\ReleaseSystem\Site\Model\Releases $releasesModel */
		$releasesModel = $container->factory->model('Releases');
		$releasesModel->reset(true)
			->orderBy('order', 'DESC')
			->published(1)
			->access_user($container->platform->getUser()->id)
			->category_id(1)
			->maturity('stable');

		$releases = $releasesModel->get(true);

		$releaseList = [];

		// Prepare signature link
		$signatureLink = Uri::base() . "v1/signatures/cms/%s";

		// Process release list
		if ($releases->count())
		{
			/** @var \Akeeba\ReleaseSystem\Site\Model\Releases $release */
			foreach ($releases as $release)
			{
				// Create new DateTime object to convert release date to swagger-compatible format
				$releaseDate = new DateTime($release->created, new DateTimeZone('UTC'));

				$releaseList[] = [
					'version' => $release->version,
					'branch' => $release->category->title,
					'date' => $releaseDate->format(DateTime::RFC3339),
					'relationships' => [
						'signatures' => sprintf($signatureLink, $release->alias)
					]
				];
			}
		}

		// Now build the response
		$item = [
			'total' => $releases->count(),
			'releases' => $releaseList
		];

		// Load the item into the document's buffer
		$this->getApplication()->getDocument()->setBuffer($item);

		return true;
	}
```
So this update is not on the live site... so where are you looking at this time. Since I know the data on the sandbox site is not coherent to the live system.

**Comment by zero-24** [comment]
@HLeithner can it be that you deployed it different than it was in this PR?

**Comment by Llewellynvdm** [comment]
Okay so I just hand coded the change to the live site, and the reposed change is not a fix.

**Comment by Llewellynvdm** [comment]
Unless there is a cache of the API... but to me it seems like it returns the same values...

**Comment by Llewellynvdm** [comment]
So I can confirm that this change is not working:
```php
public function execute()
{
	// This will autoload the ARS files
	$container = Container::getInstance('com_ars');

	/** @var \Akeeba\ReleaseSystem\Site\Model\Releases $releasesModel */
	$releasesModel = $container->factory->model('Releases');
	$releasesModel->reset(true)
		->orderBy('order', 'DESC')
		->published(1)
		->access_user($container->platform->getUser()->id)
		->visualgroup_id(1)
		->maturity('stable');
```

**Comment by HLeithner** [comment]
I did a fix on the live site but it's not nice, so finding out how to do it with visualgroup (or multiple categories) would be great.

**Comment by zero-24** [comment]
What has been deployed now to the live site?

**Comment by HLeithner** [comment]
A loop over the 4 categories...

**Comment by zero-24** [comment]
Ok so 4 categories didnt work too

**Comment by HLeithner** [comment]
What you mean, now all releases are shown.

**Pull request merged**
