### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by zero-24**
cc @wilsonge @HLeithner I'm not sure why the handler was chnaged to 7.0 but thats the live config on the site.

PS the change here is adding img-src data: thats deployed live already.

### CODE REVIEW

**Comment by conconnl** [comment]
I removed them, they are not used anymore.
Cloudlinux is now managing the PHP part.

**Comment by zero-24** [comment]
@wilsonge @HLeithner once merged please update the server too.

**Comment by conconnl** [comment]
I did and checked if it kept working

**Comment by conconnl** [comment]
Thanks @zero-24 i guess we should check the other sites as well. I had to do this change to CJO as well to make 2FA work.

**Pull request merged**
