### PR TITLE
Update ars-categories.php

### PR DESCRIPTION
**Pull request by conconnl**
Description update & Cleanup
Added missing J3 Languages

### CODE REVIEW

**Comment by conconnl** [comment]
@wilsonge I also added the missing categories manually in the ARS component and checked if the S3 folders exist

**Comment by wilsonge** [comment]
Let's test running this on the sandbox site (be careful to check for any changes in the existing categories in case people have manually changed data in the meantime).

**Comment by conconnl** [comment]
What is the real purpose if this file?

I mean do we really need to keep updating it, when adding new categories in the system (via backend).
I understand it's easy for a developer to update this file and then run it to get the changes in the site, at the same time the amount of categories which are being added is not much. So, isn't it enough to just add a category to the system when needed and not this file anymore.

**Comment by conconnl** [comment]
Merged to have the data up-to-date.
Running the file isn't needed anymore

**Pull request merged**
